language: node_js
node_js:
- '4.4'
sudo: false
before_install:
- npm install -g npm@2.13.5
- npm install -g grunt-cli
install: npm install
services:
- docker
- mongodb
script:
- npm run bootstrap
- npm test
cache:
  directories:
    - apps/raincatcher-demo-auth/node_modules
    - apps/raincatcher-demo-cloud/node_modules
    - apps/raincatcher-demo-mobile/node_modules
    - apps/raincatcher-demo-portal/node_modules
    - packages/raincatcher-analytics/node_modules
    - packages/raincatcher-appform/node_modules
    - packages/raincatcher-camera/node_modules
    - packages/raincatcher-file/node_modules
    - packages/raincatcher-gps/node_modules
    - packages/raincatcher-map/node_modules
    - packages/raincatcher-mediator/node_modules
    - packages/raincatcher-message/node_modules
    - packages/raincatcher-mongoose-store/node_modules
    - packages/raincatcher-push/node_modules
    - packages/raincatcher-result/node_modules
    - packages/raincatcher-risk-assessment/node_modules
    - packages/raincatcher-schedule/node_modules
    - packages/raincatcher-signature/node_modules
    - packages/raincatcher-simple-store/node_modules
    - packages/raincatcher-sync/node_modules
    - packages/raincatcher-template-build/node_modules
    - packages/raincatcher-tutorial-client/node_modules
    - packages/raincatcher-tutorial-cloud/node_modules
    - packages/raincatcher-tutorial-module/node_modules
    - packages/raincatcher-user/node_modules
    - packages/raincatcher-vehicle-inspection/node_modules
    - packages/raincatcher-workflow/node_modules
    - packages/raincatcher-workorder/node_modules
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: dyx1AOu9KCH35qtYek36XdMu+xQH99B3DeD+Z7C3n5lYN1FGe7rmOqR6pr5yvuBzJZ1Q1JWoelVNbLYGLcGSKmjMvmAzpAUF4bHUNixUYQx3e5BFYQFAoeaIG4Ksosi7EOIIt7f8MC0/UmXMarSyz8YP4kK39RbVRRDbGtfyTE/Tw7mJ8xpgp4crmViKnbt3QY1gosppDQnlBYQGeSmQd9zpmxo+QSU0vH+9Cpwk5nR8PjSzJK0X/HBWum865NK2cNRHwgTlxBVq5S+P0dseT9zHmEXtWLJSgEFLmo27PFQYb9x9Y5yi/pQtKuOSw4JwluFoSR9LlCon2qTK+ULyONQqaBWUtrUAPgxc+2S4hebelFzFGFWTpNoC5v+oN46yAuIazVl+4NKGfKWBni8CS2W1IVizFxnFGhg6GKgzPeyvQWokyAO5J3pnlBWr5melJWsfxwAP4iMSF7oNF8obXuvlZtF/ZHiYCOIXtb8eKjJePI3o6B7nPgQ/OD2hqjdHzjE+Q0LoqytphPQWLTwjsBOs8kHXWdxMdXgSCnqdNVj70V0+7AnHG1AOKjcbVfhcL4nD9KH4WKg9mMF1aykouHEawlpv6P0QQoi5YOGkABWR1basE3qxlqhStRcu6iWGUrAV1JGlt6bKwdln2uFZppKCmQbWZSTXHANJXCD5qc0=
